# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 18:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maturity', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('W', 'Pending'), ('P', 'Paid'), ('F', 'Forgiven')], default='W', max_length=1)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Charter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=10, verbose_name='Land area percentage')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offeror_as_bond', models.BooleanField(default=False)),
                ('offeror_as_bond_maturity', models.IntegerField(default=0)),
                ('offeree_as_bond', models.BooleanField(default=False)),
                ('offeree_as_bond_maturity', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('U', 'Unknown'), ('W', 'Waiting'), ('A', 'Accepted'), ('R', 'Rejected'), ('C', 'Canceled')], default='U', max_length=1)),
                ('offeree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('offeree_bond', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Bond')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delinquency', models.IntegerField(default=0, help_text='Number of delinquent bonds as creditor. The rate of delinquency (delinquent bonds over total paid bonds) affects the credit quality of the player.', verbose_name='Delinquent bonds')),
            ],
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.IntegerField(default=0, verbose_name='Currency')),
                ('wood1', models.IntegerField(default=0, verbose_name='Wood I')),
                ('wood2', models.IntegerField(default=0, verbose_name='Wood II')),
                ('wood3', models.IntegerField(default=0, verbose_name='Wood III')),
                ('stone1', models.IntegerField(default=0, verbose_name='Stone I')),
                ('stone2', models.IntegerField(default=0, verbose_name='Stone II')),
                ('gems', models.IntegerField(default=0, verbose_name='Gems')),
                ('spices', models.IntegerField(default=0, verbose_name='Spices')),
                ('coffee', models.IntegerField(default=0, verbose_name='Coffee')),
                ('yerba_mate', models.IntegerField(default=0, verbose_name='Yerba mate')),
                ('alcohol', models.IntegerField(default=0, verbose_name='Alcohol')),
                ('salt', models.IntegerField(default=0, verbose_name='Salt')),
                ('opium', models.IntegerField(default=0, verbose_name='Opium')),
                ('tea', models.IntegerField(default=0, verbose_name='Tea')),
                ('pearls', models.IntegerField(default=0, verbose_name='Pearls')),
                ('perfumery', models.IntegerField(default=0, verbose_name='Perfumery')),
                ('textilesI', models.IntegerField(default=0, verbose_name='Textiles I')),
                ('textilesII', models.IntegerField(default=0, verbose_name='Textiles II')),
                ('craft', models.IntegerField(default=0, verbose_name='Craft')),
                ('ore', models.IntegerField(default=0, verbose_name='Ore')),
                ('coal', models.IntegerField(default=0, verbose_name='Coal')),
                ('metal1', models.IntegerField(default=0, verbose_name='Metal')),
                ('metal2', models.IntegerField(default=0, verbose_name='Precious Metal')),
                ('food', models.IntegerField(default=0, verbose_name='Food')),
                ('fibre', models.IntegerField(default=0, verbose_name='Fibre')),
                ('guano', models.IntegerField(default=0, verbose_name='Guano')),
                ('saltpetre', models.IntegerField(default=0, verbose_name='Saltpetre')),
                ('sulfur', models.IntegerField(default=0, verbose_name='Sulfur')),
                ('gunpowder', models.IntegerField(default=0, verbose_name='Gunpowder')),
            ],
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('land_area', models.IntegerField(default=100, verbose_name='Land area')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='resources',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.Resources'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exchange',
            name='offeree_resources',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Resources'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='offeree_territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Territory'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='offeror',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exchange',
            name='offeror_bond',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Bond'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='offeror_resources',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Resources'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='offeror_territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Territory'),
        ),
        migrations.AddField(
            model_name='charter',
            name='territory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Territory'),
        ),
        migrations.AddField(
            model_name='bond',
            name='resources',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Resources'),
        ),
        migrations.AddField(
            model_name='bond',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='game.Territory'),
        ),
    ]
